#!/bin/bash
read X
read Y
if [ $X == $Y ]
then
   echo "X is equal to Y"
elif [ $X -gt $Y ]
then
   echo "X is greater than Y"
elif [ $X -lt $Y ]
then
   echo "X is less than Y"
else
   echo "None of the condition met"
fi